//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8_1
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mosReqObjList
    {

        /// <remarks/>
        public string queryID;

        /// <remarks/>
        public int listReturnStart;

        /// <remarks/>
        public int listReturnEnd;

        /// <remarks/>
        public string generalSearch;

        /// <remarks/>
        public string mosSchema;

        /// <remarks/>
#if false//Generated from the XSD.exe tool - the typeof should contain an array of searchField but it does not
          [System.Xml.Serialization.XmlArrayItemAttribute("searchField", typeof(searchField), IsNullable=false)]
#else//manually corrected to provide a typeof an array of the searchField type.
        [System.Xml.Serialization.XmlArrayItemAttribute("searchField", typeof(searchField[]), IsNullable = false)]
#endif
        public searchField[][] searchGroup;

    }

}