//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mosObj
    {

        /// <remarks/>
        public string objID;

        /// <remarks/>
        public string objSlug;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElement()]
        public System.Xml.XmlElement mosAbstract;

        /// <remarks/>
        public string objGroup;

        /// <remarks/>
        public string objType;

        /// <remarks/>
        public string objTB;

        /// <remarks/>
        public string objRev;

        /// <remarks/>
        public string objDur;

        /// <remarks/>
        public string status;

        /// <remarks/>
        public string objAir;

        /// <remarks/>
        public string createdBy;

        /// <remarks/>
        public string created;

        /// <remarks/>
        public string changedBy;

        /// <remarks/>
        public string changed;

        /// <remarks/>
        public description description;
    }
}