//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_5
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mos
    {
        /// <remarks/>
        public string mosID;

        /// <remarks/>
        public string ncsID;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heartbeat", typeof(heartbeat))]
        [System.Xml.Serialization.XmlElementAttribute("listMachInfo", typeof(listMachInfo))]
        [System.Xml.Serialization.XmlElementAttribute("mosAck", typeof(mosAck))]
        [System.Xml.Serialization.XmlElementAttribute("mosListAll", typeof(mosListAll))]
        [System.Xml.Serialization.XmlElementAttribute("mosObj", typeof(mosObj))]
        [System.Xml.Serialization.XmlElementAttribute("mosObjCreate", typeof(mosObjCreate))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqAll", typeof(mosReqAll))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqObj", typeof(mosReqObj))]
        [System.Xml.Serialization.XmlElementAttribute("reqMachInfo", typeof(reqMachInfo))]
        [System.Xml.Serialization.XmlElementAttribute("roAck", typeof(roAck))]
        [System.Xml.Serialization.XmlElementAttribute("roCreate", typeof(roCreate))]
        [System.Xml.Serialization.XmlElementAttribute("roCtrl", typeof(roCtrl))]
        [System.Xml.Serialization.XmlElementAttribute("roDelete", typeof(roDelete))]
        [System.Xml.Serialization.XmlElementAttribute("roItemCue", typeof(roItemCue))]
        [System.Xml.Serialization.XmlElementAttribute("roItemStat", typeof(roItemStat))]
        [System.Xml.Serialization.XmlElementAttribute("roList", typeof(roList))]
        [System.Xml.Serialization.XmlElementAttribute("roListAll", typeof(roListAll))]
        [System.Xml.Serialization.XmlElementAttribute("roReadyToAir", typeof(roReadyToAir))]
        [System.Xml.Serialization.XmlElementAttribute("roReplace", typeof(roReplace))]
        [System.Xml.Serialization.XmlElementAttribute("roReq", typeof(roReq))]
        [System.Xml.Serialization.XmlElementAttribute("roReqAll", typeof(roReqAll))]
        [System.Xml.Serialization.XmlElementAttribute("roStat", typeof(roStat))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryAppend", typeof(roStoryAppend))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryDelete", typeof(roStoryDelete))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryInsert", typeof(roStoryInsert))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryMoveMultiple", typeof(roStoryMoveMultiple))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryReplace", typeof(roStoryReplace))]
        [System.Xml.Serialization.XmlElementAttribute("roStorySend", typeof(roStorySend))]
        public object Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string changeDate;

        public mos()
        {
            this.version = "-//MOS Group//DTD MOS 2.5//EN";
            this.changeDate = "31 October 2000";
        }
    }
}