//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_6
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mosListAll
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objID")]
        public string[] objID;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objSlug")]
        public string[] objSlug;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mosAbstract")]
        public System.Xml.XmlElement[] mosAbstract;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objGroup")]
        public string[] objGroup;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objType")]
        public objType[] objType;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objTB")]
        public int[] objTB;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objRev")]
        public int[] objRev;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objDur")]
        public int[] objDur;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public string[] status;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objAir")]
        public objAir[] objAir;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("createdBy")]
        public string[] createdBy;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("created")]
        public System.String[] created;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("changedBy")]
        public string[] changedBy;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("changed")]
        public System.String[] changed;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description")]
        public description[] description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mosExternalMetadata")]
        public mosExternalMetadata[] mosExternalMetadata;
    }
}