//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mosObjList
    {

        /// <remarks/>
        public string queryID;

        /// <remarks/>
        public int listReturnStart;

        /// <remarks/>
        public int listReturnEnd;

        /// <remarks/>
        public int listReturnTotal;

        /// <remarks/>
        public string listReturnStatus;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mosObj", IsNullable = false)]
        public mosObj[] list;

    }
}