//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8_2
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class listMachInfo
    {

        /// <remarks/>
        public string manufacturer;

        /// <remarks/>
        public string model;

        /// <remarks/>
        public string hwRev;

        /// <remarks/>
        public string swRev;

        /// <remarks/>
        public string DOM;

        /// <remarks/>
        public string SN;

        /// <remarks/>
        public string ID;

        /// <remarks/>
        public string time;

        /// <remarks/>
        public string opTime;

        /// <remarks/>
        public string mosRev;

        /// <remarks/>
        public string mosProfile0;

        /// <remarks/>
        public string mosProfile1;

        /// <remarks/>
        public string mosProfile2;

        /// <remarks/>
        public string mosProfile3;

        /// <remarks/>
        public string mosProfile4;

        /// <remarks/>
        public string mosProfile5;

        /// <remarks/>
        public string mosProfile6;

        /// <remarks/>
        public string mosProfile7;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("defaultActiveX")]
        public defaultActiveX[] defaultActiveX;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mosExternalMetadata")]
        public mosExternalMetadata[] mosExternalMetadata;
    }
}