//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8_2
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mos
    {
        /// <remarks/>
        public string mosID;

        /// <remarks/>
        public string ncsID;

        /// <remarks/>
        public int messageID;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heartbeat", typeof(heartbeat))]
        [System.Xml.Serialization.XmlElementAttribute("listMachInfo", typeof(listMachInfo))]
        [System.Xml.Serialization.XmlElementAttribute("mosAck", typeof(mosAck))]
        [System.Xml.Serialization.XmlElementAttribute("mosItemReplace", typeof(mosItemReplace))]
        [System.Xml.Serialization.XmlElementAttribute("mosListAll", typeof(mosListAll))]
        [System.Xml.Serialization.XmlElementAttribute("mosListSearchableSchema", typeof(mosListSearchableSchema))]
        [System.Xml.Serialization.XmlElementAttribute("mosObj", typeof(mosObj))]
        [System.Xml.Serialization.XmlElementAttribute("mosObjCreate", typeof(mosObjCreate))]
        [System.Xml.Serialization.XmlElementAttribute("mosObjList", typeof(mosObjList))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqAll", typeof(mosReqAll))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqObj", typeof(mosReqObj))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqObjAction", typeof(mosReqObjAction))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqObjList", typeof(mosReqObjList))]
        [System.Xml.Serialization.XmlElementAttribute("mosReqSearchableSchema", typeof(mosReqSearchableSchema))]
        [System.Xml.Serialization.XmlElementAttribute("ncsAck", typeof(ncsAck))]
        [System.Xml.Serialization.XmlElementAttribute("ncsAppInfo", typeof(ncsAppInfo))]
        [System.Xml.Serialization.XmlElementAttribute("ncsItem", typeof(ncsItem))]
        [System.Xml.Serialization.XmlElementAttribute("ncsItemRequest", typeof(ncsItemRequest))]
        [System.Xml.Serialization.XmlElementAttribute("ncsReqAppClose", typeof(ncsReqAppClose))]
        [System.Xml.Serialization.XmlElementAttribute("ncsReqAppInfo", typeof(ncsReqAppInfo))]
        [System.Xml.Serialization.XmlElementAttribute("ncsReqAppMode", typeof(ncsReqAppMode))]
        [System.Xml.Serialization.XmlElementAttribute("ncsStoryRequest", typeof(ncsStoryRequest))]
        [System.Xml.Serialization.XmlElementAttribute("reqMachInfo", typeof(reqMachInfo))]
        [System.Xml.Serialization.XmlElementAttribute("roAck", typeof(roAck))]
        [System.Xml.Serialization.XmlElementAttribute("roCreate", typeof(roCreate))]
        [System.Xml.Serialization.XmlElementAttribute("roCtrl", typeof(roCtrl))]
        [System.Xml.Serialization.XmlElementAttribute("roDelete", typeof(roDelete))]
        [System.Xml.Serialization.XmlElementAttribute("roElementAction", typeof(roElementAction))]
        [System.Xml.Serialization.XmlElementAttribute("roItemCue", typeof(roItemCue))]
        [System.Xml.Serialization.XmlElementAttribute("roItemDelete", typeof(roItemDelete))]
        [System.Xml.Serialization.XmlElementAttribute("roItemInsert", typeof(roItemInsert))]
        [System.Xml.Serialization.XmlElementAttribute("roItemMoveMultiple", typeof(roItemMoveMultiple))]
        [System.Xml.Serialization.XmlElementAttribute("roItemReplace", typeof(roItemReplace))]
        [System.Xml.Serialization.XmlElementAttribute("roItemStat", typeof(roItemStat))]
        [System.Xml.Serialization.XmlElementAttribute("roList", typeof(roList))]
        [System.Xml.Serialization.XmlElementAttribute("roListAll", typeof(roListAll))]
        [System.Xml.Serialization.XmlElementAttribute("roMetadataReplace", typeof(roMetadataReplace))]
        [System.Xml.Serialization.XmlElementAttribute("roReadyToAir", typeof(roReadyToAir))]
        [System.Xml.Serialization.XmlElementAttribute("roReplace", typeof(roReplace))]
        [System.Xml.Serialization.XmlElementAttribute("roReq", typeof(roReq))]
        [System.Xml.Serialization.XmlElementAttribute("roReqAll", typeof(roReqAll))]
        [System.Xml.Serialization.XmlElementAttribute("roReqStoryAction", typeof(roReqStoryAction))]
        [System.Xml.Serialization.XmlElementAttribute("roStat", typeof(roStat))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryAppend", typeof(roStoryAppend))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryDelete", typeof(roStoryDelete))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryInsert", typeof(roStoryInsert))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryMove", typeof(roStoryMove))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryMoveMultiple", typeof(roStoryMoveMultiple))]
        [System.Xml.Serialization.XmlElementAttribute("roStoryReplace", typeof(roStoryReplace))]
        [System.Xml.Serialization.XmlElementAttribute("roStorySend", typeof(roStorySend))]
        [System.Xml.Serialization.XmlElementAttribute("roStorySwap", typeof(roStorySwap))]
        public object Item;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string changeDate;

        public mos()
        {
            this.version = "-//MOS Group//DTD MOS 2.8.2//EN";
            this.changeDate = "09 April 2005";
        }
    }
}