//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8_2
{
    using System.Xml.Serialization;
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class mosReqObjAction
    {

        /// <remarks/>
        public string objSlug;

        /// <remarks/>
        public System.Xml.XmlElement mosAbstract;

        /// <remarks/>
        public string objGroup;

        /// <remarks/>
        public objType objType;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objTypeSpecified;

        /// <remarks/>
        public int objTB;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objTBSpecified;

        /// <remarks/>
        public int objDur;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objDurSpecified;

        /// <remarks/>
        public System.String time;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified;

        /// <remarks/>
        public string createdBy;

        /// <remarks/>
        public string changedBy;

        /// <remarks/>
        public System.String changed;

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool changedSpecified;

        /// <remarks/>
        public description description;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mosExternalMetadata")]
        public mosExternalMetadata[] mosExternalMetadata;


        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public mosReqObjActionOperation operation;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string objID;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum mosReqObjActionOperation
    {

        /// <remarks/>
        NEW,

        /// <remarks/>
        UPDATE,

        /// <remarks/>
        DELETE,
    }
}