//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace OSM.MOSProtocol.Messages.MOS_2_8_3
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        b,

        /// <remarks/>
        em,

        /// <remarks/>
        i,

        /// <remarks/>
        pi,

        /// <remarks/>
        pkg,

        /// <remarks/>
        tab,

        /// <remarks/>
        u,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType1
    {

        /// <remarks/>
        em,

        /// <remarks/>
        p,

        /// <remarks/>
        tab,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType2
    {

        /// <remarks/>
        item,

        /// <remarks/>
        itemID,

        /// <remarks/>
        story,

        /// <remarks/>
        storyID,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType3
    {

        /// <remarks/>
        p,

        /// <remarks/>
        storyItem,

        /// <remarks/>
        storyPresenter,

        /// <remarks/>
        storyPresenterRR,
    }
#if false
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType3
    {

        /// <remarks/>
        heartbeat,

        /// <remarks/>
        listMachInfo,

        /// <remarks/>
        messageID,

        /// <remarks/>
        mosAck,

        /// <remarks/>
        mosID,

        /// <remarks/>
        mosItemReplace,

        /// <remarks/>
        mosListAll,

        /// <remarks/>
        mosListSearchableSchema,

        /// <remarks/>
        mosObj,

        /// <remarks/>
        mosObjCreate,

        /// <remarks/>
        mosObjList,

        /// <remarks/>
        mosReqAll,

        /// <remarks/>
        mosReqObj,

        /// <remarks/>
        mosReqObjAction,

        /// <remarks/>
        mosReqObjList,

        /// <remarks/>
        mosReqSearchableSchema,
        
        /// <remarks/>
        ncsID,

        /// <remarks/>
        reqMachInfo,

        /// <remarks/>
        roAck,

        /// <remarks/>
        roCreate,

        /// <remarks/>
        roCtrl,

        /// <remarks/>
        roDelete,

        /// <remarks/>
        roElementAction,

        /// <remarks/>
        roElementStat,

        /// <remarks/>
        roItemCue,

        /// <remarks/>
        roItemDelete,

        /// <remarks/>
        roItemInsert,

        /// <remarks/>
        roItemMoveMultiple,

        /// <remarks/>
        roItemReplace,

        /// <remarks/>
        roItemStat,

        /// <remarks/>
        roList,

        /// <remarks/>
        roListAll,

        /// <remarks/>
        roMetadataReplace,

        /// <remarks/>
        roReadyToAir,

        /// <remarks/>
        roReplace,

        /// <remarks/>
        roReq,

        /// <remarks/>
        roReqAll,

        /// <remarks/>
        roReqStoryAction,

        /// <remarks/>
        roStat,

        /// <remarks/>
        roStoryAppend,

        /// <remarks/>
        roStoryDelete,

        /// <remarks/>
        roStoryInsert,

        /// <remarks/>
        roStoryMove,

        /// <remarks/>
        roStoryMoveMultiple,

        /// <remarks/>
        roStoryReplace,

        /// <remarks/>
        roStorySend,

        /// <remarks/>
        roStorySwap,
    }
#endif
}